name: Docs

'on':
  push:
    # tags:
    #  - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Poetry
        uses: jayclassless/setup-poetry-action@v1

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install
        run: |
          make setup
          make env

      - name: Build Docs
        run: |
          make docs

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: docs/build/html
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
